### ISSUE TITLE
cloud resource connection time out

### ISSUE THREAD

**Issue by yxu02** [Mcronk/Trusted_AI_5-28-2020#1]
In lab 2 it supposed to download data from IBM cloud. Here is the code:
`res=cos.download_file(Bucket=credentials['BUCKET'],Key=credentials['FILE_TRAIN'],Filename='training_file')
res=cos.download_file(Bucket=credentials['BUCKET'],Key=credentials['FILE_VALID'],Filename='valid_file')
res=cos.download_file(Bucket=credentials['BUCKET'],Key=credentials['FILE_TEST'],Filename='testing_file')
res=cos.download_file(Bucket=credentials['BUCKET'],Key=credentials['FILE_SIGN'],Filename='classname_file')
res=cos.download_file(Bucket=credentials['BUCKET'],Key=credentials['FILE_SIGN_ALL'],Filename='signnames_all_file')
res=cos.download_file(Bucket=credentials['BUCKET'],Key=credentials['MODEL_META'],Filename='checkpoints/final.ckpt.meta')
res=cos.download_file(Bucket=credentials['BUCKET'],Key=credentials['MODEL_DATA'],Filename='checkpoints/final.ckpt.data-00000-of-00001')
res=cos.download_file(Bucket=credentials['BUCKET'],Key=credentials['MODEL_CHECKPOINT'],Filename='checkpoints/checkpoint')
res=cos.download_file(Bucket=credentials['BUCKET'],Key=credentials['MODEL_CKPT_INDEX'],Filename='checkpoints/final.ckpt.index')
res=cos.download_file(Bucket=credentials['BUCKET'],Key=credentials['FILE_STOP'],Filename='stop_001.png')
res=cos.download_file(Bucket=credentials['BUCKET'],Key=credentials['FILE_DIAG_1'],Filename='diagram1.png')
res=cos.download_file(Bucket=credentials['BUCKET'],Key=credentials['FILE_DIAG_2'],Filename='diagram2.png')`

However, this will time out. Please address the issue.

**Comment by Mcronk** [comment]
We create new repos for each of our workshops as we give them. Here is the most recent one for the "Trusted AI" materials: https://github.com/bleonardb3/TR_POT_10-15-2020
